name: Run Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./server  # Set working directory to 'server'

      - name: Run scraper.py
        run: |
          python scraper/scraper.py
        working-directory: ./server  # Ensure the script runs from 'server'
