name: Run Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./server  # Set working directory to 'server'

      - name: Run scraper.py
        run: |
          python scraper/scraper.py
        working-directory: ./server  # Ensure the script runs from 'server'

      - name: Commit and Push if Changed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Access token stored in GitHub secrets
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add client/src/data/articles.json  # Adjusted to the actual relative path
          git diff --staged --quiet || (git commit -m "Update articles.json [CI]" && git push https://github.com/johnwaugh1/TechTidings.git HEAD:main --token $GH_TOKEN)
